### ISSUE TITLE
Add ability to collect airdrop or other random token to feeRecipient

### ISSUE THREAD

**Issue by antoncoding** [hodlmybeer/hodl#17]

**Comment by alxkzmn** [comment]
Do you mean sweeping everything that falls into the contract to the recipient address?

**Comment by antoncoding** [comment]
yeah ;)

**Comment by antoncoding** [comment]
I think we have 2 obvious options: 
1. send it to the fee recipient
2. let the fee recipient decide where it goes.

I think 1 is probably enough because I imagine in the future we will setup a "treasury" as fee recipient for all token holders

**Comment by alxkzmn** [comment]
Agreed, 1st is enough, at least for the beginning.
